export const siteConfig = {
  name: 'Project 42',
  tagline: 'Не ещё одна веб-студия',
  description:
    'Решаем задачи бизнеса, а не просто делаем сайты. Полный цикл: дизайн, разработка, SEO, GEO-оптимизация и поддержка. Не конвейер — не более 4 проектов одновременно.',
  url: 'https://project42-studio.ru',
  email: 'project42studio@gmail.com',
  founderName: 'Иван Нарчук',
  legalName: 'Нарчук Иван Валериевич',
  addressLocality: 'Москва',
  addressCountry: 'RU',
  locale: 'ru_RU',
  twitterHandle: '@project42studio',
  sameAs: [
    'https://t.me/ivann97n',
    'https://max.ru/u/f9LHodD0cOJ3bESpnMANQoyejFdeTcoGRFmNOyMIWRGnFX8VmxGipv3OHNA',
    'https://wa.me/79998589878',
  ] as string[],
  services: [
    'Разработка сайтов',
    'UI/UX дизайн',
    'SEO-продвижение',
    'GEO-оптимизация',
    'Настройка Яндекс Директ',
    'Поддержка и развитие сайтов',
  ] as string[],
  keywords: [
    'веб-студия',
    'разработка сайтов под ключ',
    'создание корпоративного сайта',
    'создание лендинга',
    'ui/ux дизайн',
    'seo продвижение сайта',
    'geo оптимизация',
    'яндекс директ',
    'поддержка сайтов',
    'долгосрочное партнёрство',
  ] as string[],
} as const
